sudo: required
dist: trusty
language: python
install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3 python3.5 python3.6 python3-pip npm php-pear python-setuptools python3-setuptools
  - pip install tox
  - npm install -g jshint jscs jscs-fixer csscomb htmlcs walk brace-expansion
  - sudo pear install PHP_CodeSniffer
script:
  - tox
